### ISSUE TITLE
Add support for raw POST requests

### ISSUE THREAD

**Issue by kmike** [tswicegood/Dolt#5]
Some APIs require sending raw POST requests (with e.g. xml or binary data), but now Dolt supports only `application/x-www-form-urlencoded` POST data  in key=value format. 

It can be resolved by adding 'RAW_POST' request method:

```
def __init__(self, *args, **kwargs):
    super(MyDolt, self).__init__(*args, **kwargs)
    self._supported_methods += ('RAW_POST',)

def _generate_body(self):
    if self._method == 'RAW_POST':
        self._method = 'POST'
        return self._params['data']
    return super(MyDolt, self)._generate_body()
```

Usage:

```
api.method.RAW_POST(data=my_data)    
```

I think this can be a good addition to Dolt itself. Will you accept pull request with this addition? Or maybe there is a way to handle raw POST requests better?

Edit: I removed magic 'RAW' attribute method because it is flawed (it will make APIs that uses 'RAW' in url unusable).

**Comment by tswicegood** [comment]
I like this.  Do you want to take a stab at it?

**Comment by tswicegood** [comment]
This is now possible via the `with_body` method in v0.7.0
