### ISSUE TITLE
Non-obvious choice or request method

### ISSUE THREAD

**Issue by kmike** [tswicegood/Dolt#9]
Example:

```
post_result = api.POST.resource(foo=bar)
get_result = api.resource() # this will generate POST request because self._method is preserved
```

Quick fix is to reset self._method to 'GET' after calling. I think the cleanest fix for such bugs is to return a new Dolt instance on each `__getattr__`and`**getitem**`, this will resolve the following non-obvious behavior as well:

```
api.foo
api.bar() # this will fetch /foo/bar
```

**Comment by tswicegood** [comment]
I think this is addressed by the cloneable changes in #10.  Please re-open if I'm wrong.
